//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCGA.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.Afiliado = new HashSet<Afiliado>();
            this.Bono = new HashSet<Bono>();
            this.HistorialAfiliado = new HashSet<HistorialAfiliado>();
        }
    
        public int Id { get; set; }
        public string descripcion { get; set; }
        public decimal precio_bono_consulta { get; set; }
        public decimal precio_bono_farmacia { get; set; }
        [ScaffoldColumn(false)]
        public System.DateTime createdon { get; set; }
        [ScaffoldColumn(false)]
        public string createdby { get; set; }
        [ScaffoldColumn(false)]
        public System.DateTime changedon { get; set; }
        [ScaffoldColumn(false)]
        public string changedby { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> deletedon { get; set; }
        [ScaffoldColumn(false)]
        public string deletedby { get; set; }
        [ScaffoldColumn(false)]
        public bool isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Afiliado> Afiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bono> Bono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAfiliado> HistorialAfiliado { get; set; }
    }
}
